spring:
  application:
    name: iss-policy-search-service
  main:
    banner-mode: "off"
  cloud:
    stream:   
      kafka:
        binder:
          brokers: ${KAFKA_HOST:localhost}:${KAFKA_PORT:9092}
      bindings:
        policy-registered-in:
          destination: policy-registered
          contentType: application/json
          group: policy
          consumer:
            partitioned: true
            concurrency: 5
            auto.offset.reset: earliest 
        policy-terminated-in:
          destination: policy-terminated
          contentType: application/json
          group: policy
          consumer:
            partitioned: true
            concurrency: 5
            auto.offset.reset: earliest   
          
elasticsearch:
     repository:
        enabled: false             